### PR TITLE
2 min breaks

### PR DESCRIPTION
**Pull request by gammaw**

### CODE REVIEW

**Review by pvj — CHANGES_REQUESTED** [review]
Looks good! Please also change transverszia which has an unusual end time so I guess replace operation skipped it, otherwise happy to release this finally!

**Comment by baxgas** [comment]
Looks fine to me also.
Don't know if Transversia is a problem, it doesn't have this 1-2 min gap until the next show, so it is not an issue here. But could be done for consistency...

**Comment by gammaw** [comment]
Thanks. I overlooked transverszia as I was only searching for 29 and 59. The transverszia times didn't follow the 1-min break either, because, as baxgas said, it's not necessary there. But I agree that for consistency and also for fairness towards other shows (1-hour show has 58-minute air time) it's good to adjust it for transverszia too. 

Please review the PR again.

**Review by pvj — APPROVED** [review]
Thanks for the huge undertaking!

**Pull request merged**
